#define NULL
static __declspec;
#define dllexport
typedef size_t;
void rand();
void malloc();
void free();
void GetCursorPos();
void GetStdHandle();
void SetConsoleCursorPosition();
struct CONSOLE_CURSOR_INFO;
struct COORD:
struct POINT:
void GetConsoleCursorInfo();
void SetConsoleCursorInfo();
typedef SHORT;
typedef DWORD;
struct CONSOLE_SCREEN_BUFFER_INFO;
void GetConsoleScreenBufferInfo();