#define NULL
static __declspec;
#define dllexport
typedef size_t;
typedef int64_t;
void rand();
void memcpy();
void fflush();
void strncmp();
void strtok();
void atoi();
void strcpy();
void strlen();;
void sscanf();
void strcmp();
void exit();
void system();
void fprintf();
void perror();
void printf();
void puts();
void putc();
void malloc();
void free();
void GetCursorPos();
void GetStdHandle();
void SetConsoleCursorPosition();
struct CONSOLE_CURSOR_INFO;
struct COORD:
struct POINT:
typedef FILE;
static stdout;
static stdin;;
static stderr;;

void GetConsoleCursorInfo();
void SetConsoleCursorInfo();
typedef SHORT;
typedef DWORD;
struct CONSOLE_SCREEN_BUFFER_INFO;
void GetConsoleScreenBufferInfo();